# Singular Decomposition Value (SVD)

## Dekomposisi SVD

Untuk sebuah matriks $A$ berukuran $m \times n$, dekomposisi SVD dinyatakan sebagai:

$$
A = U \Sigma V^T
$$

>Dimana:
- $U$: Matriks ortogonal berukuran $m \times m$, kolom-kolomnya disebut **left singular vectors**
- $\Sigma$: Matriks diagonal berukuran $m \times n$, elemen-elemennya adalah **singular values**
- $V^T$: Matriks ortogonal berukuran $n \times n$, baris-barisnya disebut **right singular vectors**


## Langkah-langkah SVD


> 1. Hitung $A^T$ dan $A A^T$
2. Cari nilai eigen dan singular value ($\sigma$) dari $A^T A$  
   (catatan: singular value ($\sigma$) adalah akar dari nilai eigen $A^T A$)
3. Hitung vektor singular kanan ($V$)
4. Hitung vektor singular kiri ($U$)
5. Bangun matriks diagonal $\Sigma$
6. Verifikasi bahwa $A = U \Sigma V^T$


## SVD pada Matriks 2D
Contoh Matriks

$$
A = \begin{bmatrix}
3 & 1 \\
1 & 3
\end{bmatrix}
$$


### kegunaan dari svd
1. NLP di topik moduling
2. kompresi - nanti akan mendapatkan ciri penting

### Matriks Awal

$$
A = \begin{bmatrix}
3 & 1 \\
1 & 3
\end{bmatrix}
$$

### Mencari Transpose *A*

Transpose = baris jadi kolom:

$$
A^T = \begin{bmatrix}
3 & 1 \\
1 & 3
\end{bmatrix}
$$

Karena $A$ simetris, maka $A^T = A$.

### Hitung $A^T A$


$$A^T A = A A =
\begin{bmatrix} 3 & 1 \\ 1 & 3 \end{bmatrix}
\begin{bmatrix} 3 & 1 \\ 1 & 3 \end{bmatrix}
=\begin{bmatrix}
10 & 6 \\
6 & 10
\end{bmatrix}$$

### Cari Nilai Eigen $A^T A$

$$
\det(A^T A - \lambda I) = 0
$$

$$
\det \begin{bmatrix}
10 - \lambda & 6 \\
6 & 10 - \lambda
\end{bmatrix} = 0
$$

$$
(10 - \lambda)^2 - 36 = 0
$$

$$
(10 - \lambda)^2 = 36
$$

$$
10 - \lambda = \pm 6
$$

$$
\lambda = 10 \mp 6
$$

$$
\Rightarrow \lambda_1 = 16, \quad \lambda_2 = 4
$$

### Singular Value

$$
\sigma_1 = \sqrt{16} = 4, \quad \sigma_2 = \sqrt{4} = 2
$$

### Cari Vektor Eigen untuk $V$

Untuk $\lambda = 16$:

$$
\begin{bmatrix} -6 & 6 \\ 6 & -6 \end{bmatrix}
\Rightarrow v_1 = v_2
$$

Normalisasi:

$$
v_1 = \frac{1}{\sqrt{2}}, \quad v_2 = \frac{1}{\sqrt{2}}
$$

Untuk $\lambda = 4$:

$$
\begin{bmatrix} 6 & 6 \\ 6 & 6 \end{bmatrix}
\Rightarrow v_1 = -v_2
$$

Normalisasi:

$$
v_1 = \frac{1}{\sqrt{2}}, \quad v_2 = -\frac{1}{\sqrt{2}}
$$

### Matriks *V*

$$
V = \begin{bmatrix}
\frac{1}{\sqrt{2}} & \frac{1}{\sqrt{2}} \\
\frac{1}{\sqrt{2}} & -\frac{1}{\sqrt{2}}
\end{bmatrix}
$$

### Cari *U*

$$
U = A V \Sigma^{-1}
$$

$$
A V =
\begin{bmatrix}
2 \sqrt{2} & \sqrt{2} \\
2 \sqrt{2} & -\sqrt{2}
\end{bmatrix}
$$

Normalisasi:

$$
U = \begin{bmatrix}
\frac{1}{\sqrt{2}} & \frac{1}{\sqrt{2}} \\
\frac{1}{\sqrt{2}} & -\frac{1}{\sqrt{2}}
\end{bmatrix}
$$

### Hasil Akhir SVD

$$
A = U \Sigma V^T
$$

dengan:

$$
U = \begin{bmatrix}
\frac{1}{\sqrt{2}} & \frac{1}{\sqrt{2}} \\
\frac{1}{\sqrt{2}} & -\frac{1}{\sqrt{2}}
\end{bmatrix}, \quad
\Sigma = \begin{bmatrix}
4 & 0 \\
0 & 2
\end{bmatrix}, \quad
V = \begin{bmatrix}
\frac{1}{\sqrt{2}} & \frac{1}{\sqrt{2}} \\
\frac{1}{\sqrt{2}} & -\frac{1}{\sqrt{2}}
\end{bmatrix}
$$


### pembuktian  $A$

$A = \begin{bmatrix} 3 & 1 \\ 1 & 3 \end{bmatrix}$

$U = \frac{1}{\sqrt{2}}
\begin{bmatrix}
1 & 1 \\
1 & -1
\end{bmatrix}$

$\Sigma =
\begin{bmatrix}
4 & 0 \\
0 & 2
\end{bmatrix}$

$V = \frac{1}{\sqrt{2}}
\begin{bmatrix}
1 & 1 \\
1 & -1
\end{bmatrix}$

---

### Karena $V ortogonal, V^T = V$

Jadi:

$$
V^T = V
$$

---

### Hitung $\Sigma V^T$

$$
\Sigma V^T =
\Sigma V =
\begin{bmatrix} 4 & 0 \\ 0 & 2 \end{bmatrix}
\frac{1}{\sqrt{2}}
\begin{bmatrix} 1 & 1 \\ 1 & -1 \end{bmatrix}
$$

Hasil:

$$
= \frac{1}{\sqrt{2}}
\begin{bmatrix} 4 \cdot 1 + 0 \cdot 1 & 4 \cdot 1 + 0 \cdot (-1) \\
0 \cdot 1 + 2 \cdot 1 & 0 \cdot 1 + 2 \cdot (-1)
\end{bmatrix}
= \frac{1}{\sqrt{2}}
\begin{bmatrix} 4 & 4 \\ 2 & -2 \end{bmatrix}
$$

---

## Hitung $U \Sigma V^T$

$$
U \Sigma V^T =
\frac{1}{\sqrt{2}}
\begin{bmatrix} 1 & 1 \\ 1 & -1 \end{bmatrix}
\frac{1}{\sqrt{2}}
\begin{bmatrix} 4 & 4 \\ 2 & -2 \end{bmatrix}
$$

Karena
$$
\frac{1}{\sqrt{2}} \times \frac{1}{\sqrt{2}} = \frac{1}{2} = \frac{1}{2}
\begin{bmatrix}
1 \cdot 4 + 1 \cdot 2 & 1 \cdot 4 + 1 \cdot (-2) \\
1 \cdot 4 + (-1) \cdot 2 & 1 \cdot 4 + (-1) \cdot (-2)
\end{bmatrix}
= \frac{1}{2}
\begin{bmatrix}
6 & 2 \\
2 & 6
\end{bmatrix}
= \begin{bmatrix}
3 & 1 \\
1 & 3
\end{bmatrix} = A$$

---

## Kesimpulan

terbukti bahwa :

$$
A = U \Sigma V^T
$$

dengan hasil sesuai matriks aslinya.

### Perhitungan Singular Value Decomposition (SVD)

 Diketahui Matriks

$$
A = \begin{bmatrix}
3 & 7 \\
2 & 5 \\
4 & 3 \\
1 & 1
\end{bmatrix}
$$

## Langkah 1: Hitung \(A^T A\)

$$A^T =\begin{bmatrix}
3 & 2 & 4 & 1 \\
7 & 5 & 3 & 1
\end{bmatrix}$$

$$A^T A =\begin{bmatrix}
3 & 2 & 4 & 1 \\
7 & 5 & 3 & 1\end{bmatrix}
\begin{bmatrix}
3 & 7 \\
2 & 5 \\
4 & 3 \\
1 & 1
\end{bmatrix}=
\begin{bmatrix}
30 & 44 \\
44 & 84
\end{bmatrix}$$

### Langkah 2: Hitung Eigenvalue dari \(A^T A\)

Misal  $\lambda \text{ adalah eigenvalue dari } A^T A$

$$
\left|
\begin{array}{cc}
30 - \lambda & 44 \\
44 & 84 - \lambda
\end{array}
\right|
= 0
\Rightarrow
(30 - \lambda)(84 - \lambda) - 44^2 = 0
$$

$$
\lambda^2 - 114 \lambda + 2520 - 1936 = 0
\Rightarrow
\lambda^2 - 114 \lambda + 584 = 0
$$

$$
\lambda = \frac{114 \pm \sqrt{114^2 - 4 \cdot 584}}{2}
= \frac{114 \pm \sqrt{10660}}{2}
\Rightarrow
\lambda_1 \approx 108.62, \quad \lambda_2 \approx 5.38
$$

### Langkah 3: Hitung Singular Value

$$
\sigma_1 = \sqrt{108.62} \approx 10.42, \quad
\sigma_2 = \sqrt{5.38} \approx 2.32
$$

$$
\Sigma =
\begin{bmatrix}
10.42 & 0 \\
0 & 2.32 \\
0 & 0 \\
0 & 0
\end{bmatrix}
$$

### Langkah 4: Cari Eigenvector dari \(A^T A\)

Hasil eigenvector ter-normalisasi (dari komputasi numerik):

$$
v_1 =
\begin{bmatrix}
0.4884 \\
0.8726
\end{bmatrix}, \quad
v_2 =
\begin{bmatrix}
-0.8726 \\
0.4884
\end{bmatrix}
$$

$$
V =
\begin{bmatrix}
0.4884 & -0.8726 \\
0.8726 & 0.4884
\end{bmatrix}
$$

### Langkah 5: Hitung Matriks \(U\)

$$
u_1 = \frac{1}{10.42} A v_1, \quad
u_2 = \frac{1}{2.32} A v_2
$$

$$
u_1 \approx
\begin{bmatrix}
0.6817 \\
0.4992 \\
0.4725 \\
0.1668
\end{bmatrix}, \quad
u_2 \approx
\begin{bmatrix}
0.3241 \\
0.3882 \\
-0.3541 \\
-0.7987
\end{bmatrix}
$$

Lengkapi \(U\) menjadi matriks ortogonal \(4 \times 4\) (dengan Gram-Schmidt atau QR decomposition):

$$
U =
\begin{bmatrix}
\vec{u}_1 & \vec{u}_2 & \vec{u}_3 & \vec{u}_4
\end{bmatrix}
$$

### Langkah 6: Bentuk SVD

$$
A = U \Sigma V^T
$$

Dengan:

$$
\Sigma =
\begin{bmatrix}
10.42 & 0 \\
0 & 2.32 \\
0 & 0 \\
0 & 0
\end{bmatrix}, \quad
V^T =
\begin{bmatrix}
0.4884 & 0.8726 \\
-0.8726 & 0.4884
\end{bmatrix}
$$

### Pembuktian

$$
U \Sigma V^T = A
$$

Perkalian kembali ketiga matriks akan menghasilkan matriks semula (atau sangat mendekati secara numerik karena pembulatan).

In [ ]:
# code pembuktian
import numpy as np

# Matriks A dari soal
A = np.array([
    [3, 7],
    [2, 5],
    [4, 3],
    [1, 1]
], dtype=float)

# Langkah 1: Hitung A^T A
A_TA = A.T @ A
print("A^T A =\n", A_TA)

# Langkah 2: Hitung eigenvalue dan eigenvector A^T A
eigvals, eigvecs = np.linalg.eigh(A_TA)

# Urutkan dari terbesar ke terkecil
idx = np.argsort(eigvals)[::-1]
eigvals = eigvals[idx]
eigvecs = eigvecs[:, idx]

print("\nEigenvalues (A^T A) =", eigvals)
print("Eigenvectors (V) =\n", eigvecs)

# Langkah 3: Hitung singular value
singular_values = np.sqrt(eigvals)
print("\nSingular values =", singular_values)

# Bentuk Sigma (4x2 karena A 4x2)
Sigma = np.zeros((4, 2))
Sigma[0, 0] = singular_values[0]
Sigma[1, 1] = singular_values[1]
print("\nSigma =\n", Sigma)

# Langkah 4: Matriks V
V = eigvecs

# Langkah 5: Hitung U = (1/σ) * A * v
u1 = (A @ V[:, 0]) / singular_values[0]
u2 = (A @ V[:, 1]) / singular_values[1]

# Gabungkan jadi matriks U (4x2 untuk dua singular value)
U = np.column_stack((u1, u2))
print("\nU (2 kolom pertama) =\n", U)

# Langkah 6: Buktikan A = U Σ V^T
A_reconstructed = U @ Sigma[:2, :] @ V.T
print("\nA reconstructed =\n", A_reconstructed)

print("\nA original =\n", A)

# Hitung error rekonstruksi
error = np.linalg.norm(A - A_reconstructed)
print(f"\nReconstruction error = {error}")

A^T A =
 [[30. 44.]
 [44. 84.]]

Eigenvalues (A^T A) = [108.623638   5.376362]
Eigenvectors (V) =
 [[ 0.48835631 -0.87264432]
 [ 0.87264432  0.48835631]]

Singular values = [10.42226645  2.31869834]

Sigma =
 [[10.42226645  0.        ]
 [ 0.          2.31869834]
 [ 0.          0.        ]
 [ 0.          0.        ]]

U (2 kolom pertama) =
 [[ 0.72667296  0.34526321]
 [ 0.51235825  0.300381  ]
 [ 0.4386146  -0.87355405]
 [ 0.13058586 -0.16573437]]

A reconstructed =
 [[3. 7.]
 [2. 5.]
 [4. 3.]
 [1. 1.]]

A original =
 [[3. 7.]
 [2. 5.]
 [4. 3.]
 [1. 1.]]

Reconstruction error = 1.88411095042053e-15
